# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseLoginRegister' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseLoginRegister

  target 'FirebaseLoginRegisterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseLoginRegisterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Auth'

end
